### ISSUE TITLE
How do build dataset?

### ISSUE THREAD

**Issue by ziweiji** [DaoD/ScriptWriter#1]
If I want use another dataset (or some examples) which consists of narrative and dialogue,  I need to build dataset. where is the generated txt? Can you release the code?

**Comment by DaoD** [comment]
We provide the code in Utils.py.
function generate_data_with_random_samples(): you can use this function to generate data with random samples. 
function generate_data_with_solr_samples(): you can use this function to generate data with solr samples.
The format of the text data and vocab file are given in /data/sample_data and /data/sample_vocab, respectively.
