### ISSUE TITLE
What language is the dataset in?

### ISSUE THREAD

**Issue by patuchen** [DaoD/ScriptWriter#3]
Hello, I didn't find the information in your paper or in this repository. What language is the dataset in?

**Comment by DaoD** [comment]
Hi, it is a Chinese dataset.

**Comment by DaoD** [comment]
Hi, it is a Chinese dataset, but we provide the word ID and the corresponding embeddings.

**Comment by patuchen** [comment]
Thank you for answering. I'm in search of an English text dataset just like this, and I was hopeful while reading your paper.
